databases:
  - name: techsim_webapi_db
    databaseName: techsim_webapi_db
    user: aebibtech

services:
  - type: web
    name: techsim_webapi
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: techsim_webapi_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false